lab-configs:
- id: kvm-sno
  config: basic-lab-sno.yaml
  description: Basic Single Node Cluster on KVM
- id: kvm-3-node
  config: basic-lab-3-node.yaml
  description: Three Node Cluster with Combined Compute & Control-Plane
- id: kvm-6-node
  config: basic-lab-6-node.yaml
  description: Six Node Cluster with Separate Compute & Control-Plane
